### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by lilfmdude** [potatoeggy/mandown#45]
anyway to add https://www.perlego.com/?

i have found one i guess how it works is u need the book id and the auth id when your logged in anyway to make this work?

**Comment by lilfmdude** [comment]
more info can be seen here https://github.com/evmer/perlego-downloader this is what i mean

**Comment by potatoeggy** [comment]
Mandown is really restricted in that it's only designed to download images. Your site looks like one that is mostly text and articles, so Mandown won't be able to help you here, sorry!
