### ISSUE TITLE
The script is looking for a file with the different filename

### ISSUE THREAD

**Issue by lumpsoid** [potatoeggy/mandown#48]
When I try to load manga chapters from the source, after successfully loading the chapter images, when the script proceeds to the conversion step, it looks for `__cover.jpg`, but at the beginning it itself saves the cover with the name `cover.jpg`.
```
FileNotFoundError: [Errno 2] No such file or directory: '/home/<user>/manga/<manga_title>/__cover.jpg'
```
But the cover has the following path:
```
/home/<user>/manga/<manga_title>/cover.jpg
```

**Comment by potatoeggy** [comment]
Thank you for your bug report! I *think* I addressed the core issue in v1.1.1, so please let me know if that resolves it. AFAIK, this only happened for CBZ conversion.
