### ISSUE TITLE
[Feature Request] --convert cbz into seperate chapters

### ISSUE THREAD

**Issue by RandomLegend** [potatoeggy/mandown#63]
Hello, 

it would be great if the --convert cbz function would NOT combine every chapter into one giant .cbz file but rather takes the episode-X folders and convert them seperately creating multiple .cbz files for each chapter.

That would make it much easier and faster to load and makes it much easier to keep a manga that is still publishing up to date.

**Comment by potatoeggy** [comment]
Added in v1.4.0 in the form `mandown get ... --split-by-chapters` (shorthand `-b`) or `mandown convert ... --split-by-chapters`. Please let me know if it doesn't work!
