### ISSUE TITLE
Old version on the AUR repository

### ISSUE THREAD

**Issue by ObiSandwich** [potatoeggy/mandown#70]
**What broke?**

- [ ] Downloader
- [ ] Processor
- [ ] Converter
- [ X] Other

**Describe the bug**

Installed your cool script via Manjaro AUR, but after running `mandown --version` it looks like I'm running **v.1.3.4**

I'm having some issues with this version, so it would be good to know when will you be updating AUR with v.1.6 please?

Also, for clarity - is there a way you could add the version number somewhere in AUR please?

Cheers and keep up the good work :)

[https://aur.archlinux.org/packages/mandown-git](url)

**Comment by potatoeggy** [comment]
Thank you for opening an issue!

The 1.3.4 notice is a bug — all versions from 1.3.4 to 1.6.0 all have `mandown --version` report `1.3.4`. The AUR package automatically takes the latest commit from the master branch, so any bugs there should still be in the latest version.

I've released 1.6.1 to fix some downloader issues and update `mandown --version`. If that didn't fix your issue, please feel free to open a new issue with more details.

**Comment by ObiSandwich** [comment]
Thanks for the explanation... Does this mean I have to wait for the AUR update on my system (how long does that usually take from when you release?), or do I need to uninstall Mandown and reinstall via AUR to get the latest?

**Comment by potatoeggy** [comment]
Either works. The AUR package fetches the latest version of Mandown. If you use an AUR helper like `pacaur` or `yay` to check for updates, they will automatically check if the GitHub repo has changed and update if needed.
