### ISSUE TITLE
Please help add https://www.kuaikanmanhua.com/

### ISSUE THREAD

**Issue by syBV1** [potatoeggy/mandown#75]
I am using this tool and can you add this website to your source code: https://www.kuaikanmanhua.com/
I want to get image from this comic: https://www.kuaikanmanhua.com/webs/comic-next/432601

Thank you

**Comment by potatoeggy** [comment]
Please try `mandown get https://www.kuaikanmanhua.com/webs/comic-next/432601` in Mandown 1.8.0!

**Comment by syBV1** [comment]
Thank you for adding kuaikanmanhwa. I've always wanted to have a tool that could extract text from multiple images at the same time. For example, you put a link or path containing the images, then it will give you a .doc or .pdf file.
I'd really appreciate it if you could do that. Thank you very much

**Comment by potatoeggy** [comment]
Unfortunately, the features you're describing is outside the scope of Mandown. Sorry!
